site_name: MaxText Documentation

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.expand

docs_dir: docs

plugins:
  - search
  - include-markdown

markdown_extensions:
  - tables

nav:
  - Home: index.md
  - about.md
  - Getting started:
    - getting_started/First_run.md
    - getting_started/steps_model.md
    - End-to-end example: https://www.kaggle.com/code/melissawm/maxtext-examples
  - Advanced usage:
    - getting_started/Run_MaxText_via_multihost_job.md
    - getting_started/Run_MaxText_via_multihost_runner.md
    - getting_started/Run_MaxText_via_xpk.md
    - getting_started/Use_Vertex_AI_Tensorboard.md
    - getting_started/Run_Llama2.md
    - data_loading.md
  - Reference:
    - reference/code_organization.md
    - reference/config_options.md
    - getting_started/Data_Input_Pipeline.md
    - getting_started/Data_Input_Perf.md
